### ISSUE TITLE
Standards sweep: nft_on_transfer

### ISSUE THREAD

**Issue by mikedotexe** [near-apps/nft-market#14]
`nft_on_transfer` doesn't return `PromiseOrValue<bool>` as needed, or else if it's working, should likely be proven to work as expected.

Currently:
https://github.com/near-apps/nft-market/blob/4fb70e6a4f9b8db6fd51ccbc674dcfdcb2e1ba57/contracts/nft-simple/src/nft_core.rs#L29-L37

Spec:
https://nomicon.io/Standards/NonFungibleToken/Core.html#receiver-interface

There are a few instances of this in the `near-sdk-rs` canonical examples, but here's one:
https://github.com/near/near-sdk-rs/blob/de81ae5e21a406219911527ae4a622b1b3a2f633/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L34-L43

There's also a receiver contract in there if that's more helpful

**Comment by mattlockyer** [comment]
It returns a promise and is only used to call this self method `nft_resolve_transfer` implementation here that returns a bool:

https://github.com/near-apps/nft-market/blob/4fb70e6a4f9b8db6fd51ccbc674dcfdcb2e1ba57/contracts/nft-simple/src/nft_core.rs#L326-L372

**Comment by austinabell** [comment]
Yeah doesn't seem like anything is against standard, plus doesn't look like this boolean is even used in the callback anyway. 

@mattlockyer you are saying nothing should change here, right?

**Comment by mattlockyer** [comment]
correct, it basically works, at least in testnet live tests it will work
