### ISSUE TITLE
Build Failed 

### ISSUE THREAD

**Issue by BenKurrek** [near-apps/nft-market#2]
https://github.com/Fayyr-Organization/nft-market/commit/387510135f12a3ee4e7980db4b69fbbb9f8ca8da

I was trying to run the rust tests for the NFT-Simple contract and the build failed as shown below: 

PS C:\Users\Benjamin\Desktop\School\Fayyr\Repos\nft-market\contracts\nft-simple> cargo test -- --nocapture --color always
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling autocfg v1.0.1
   Compiling syn v1.0.57
   Compiling serde_derive v1.0.118
   Compiling serde v1.0.118
   Compiling ahash v0.4.7
   Compiling version_check v0.9.2
   Compiling typenum v1.12.0
   Compiling ryu v1.0.5
   Compiling serde_json v1.0.62
   Compiling itoa v0.4.7
   Compiling memchr v2.3.4
   Compiling block-padding v0.2.1
   Compiling opaque-debug v0.3.0
   Compiling once_cell v1.5.2
   Compiling cfg-if v1.0.0
   Compiling regex-syntax v0.6.22
   Compiling cpuid-bool v0.1.2
   Compiling hex v0.4.2
   Compiling lazy_static v1.4.0
   Compiling winapi v0.3.9
   Compiling Inflector v0.11.4
   Compiling base64 v0.11.0
   Compiling bs58 v0.4.0
   Compiling wee_alloc v0.4.5
   Compiling keccak v0.1.0
   Compiling byteorder v1.4.2
   Compiling memory_units v0.4.0
   Compiling cfg-if v0.1.10
   Compiling base64 v0.13.0
   Compiling hashbrown v0.9.1
   Compiling generic-array v0.14.4
   Compiling indexmap v1.6.1
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling num-bigint v0.3.1
   Compiling num-rational v0.3.2
   Compiling thread_local v1.1.3
   Compiling quote v1.0.8
   Compiling aho-corasick v0.7.15
   Compiling block-buffer v0.9.0
   Compiling digest v0.9.0
   Compiling regex v1.4.3
   Compiling sha2 v0.9.3
   Compiling sha3 v0.9.1
   Compiling near-runtime-utils v3.0.0
   Compiling borsh-derive-internal v0.8.1
   Compiling borsh-schema-derive-internal v0.8.1
   Compiling near-sdk-core v3.0.1
   Compiling derive_more v0.99.11
   Compiling near-sdk-macros v3.0.1
   Compiling toml v0.5.8
   Compiling near-rpc-error-core v0.1.0
   Compiling proc-macro-crate v0.1.5
   Compiling near-rpc-error-macro v0.1.0
   Compiling borsh-derive v0.8.1
   Compiling borsh v0.8.1
   Compiling near-primitives-core v0.1.0
   Compiling near-vm-errors v3.0.0
   Compiling near-vm-logic v3.0.0
   Compiling near-sdk v3.0.1
   Compiling nft_simple v0.1.0 (C:\Users\Benjamin\Desktop\School\Fayyr\Repos\nft-market\contracts\nft-simple)
error[E0061]: this function takes 5 arguments but 4 arguments were supplied
   --> src\lib.rs:209:18
    |
209 |         contract.nft_transfer(
    |                  ^^^^^^^^^^^^ expected 5 arguments
210 |             ValidAccountId::try_from(bob()).unwrap(),
    |             ----------------------------------------
211 |             "0".to_string(),
    |             ---------------
212 |             None,
    |             ----
213 |             Some("my memo".to_string()),
    |             --------------------------- supplied 4 arguments
    |
note: associated function defined here
   --> src\nft_core.rs:11:8
    |
11  |     fn nft_transfer(
    |        ^^^^^^^^^^^^

error[E0061]: this function takes 5 arguments but 4 arguments were supplied
   --> src\lib.rs:226:18
    |
226 |         contract.nft_transfer(
    |                  ^^^^^^^^^^^^ expected 5 arguments
227 |             ValidAccountId::try_from(bob()).unwrap(),
    |             ----------------------------------------
228 |             "0".to_string(),
    |             ---------------
229 |             Some(U64::from(0u64)),
    |             ---------------------
230 |             Some("my memo".to_string()),
    |             --------------------------- supplied 4 arguments
    |
note: associated function defined here
   --> src\nft_core.rs:11:8
    |
11  |     fn nft_transfer(
    |        ^^^^^^^^^^^^

error[E0061]: this function takes 5 arguments but 4 arguments were supplied
   --> src\lib.rs:273:18
    |
273 |         contract.nft_transfer(
    |                  ^^^^^^^^^^^^ expected 5 arguments
274 |             ValidAccountId::try_from(alice()).unwrap(),
    |             ------------------------------------------
275 |             "0".to_string(),
    |             ---------------
276 |             Some(U64::from(0u64)),
    |             ---------------------
277 |             Some("thanks for allowing me to take it".to_string()),
    |             ----------------------------------------------------- supplied 4 arguments
    |
note: associated function defined here
   --> src\nft_core.rs:11:8
    |
11  |     fn nft_transfer(
    |        ^^^^^^^^^^^^

error[E0061]: this function takes 5 arguments but 4 arguments were supplied
   --> src\lib.rs:310:18
    |
310 |         contract.nft_transfer(
    |                  ^^^^^^^^^^^^ expected 5 arguments
311 |             ValidAccountId::try_from(bob()).unwrap(),
    |             ----------------------------------------
312 |             "0".to_string(),
    |             ---------------
313 |             Some(U64::from(1u64)),
    |             ---------------------
314 |             Some("I am trying to hack you.".to_string()),
    |             -------------------------------------------- supplied 4 arguments
    |
note: associated function defined here
   --> src\nft_core.rs:11:8
    |
11  |     fn nft_transfer(
    |        ^^^^^^^^^^^^

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0061`.
error: could not compile `nft_simple`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by mattlockyer** [comment]
Check the readme please.

Unit tests not supported at the moment.

Only live tests against testnet.

Follow instructions.

**Comment by mattlockyer** [comment]
You might want this: https://github.com/near/core-contracts/tree/feat-approval-callbacks/nft-simple
