### ISSUE TITLE
Can't accept offer due to error 'Exceeded the prepaid gas'

### ISSUE THREAD

**Issue by baihanyi** [near-apps/nft-market#6]
I deployed this contract using the command` yarn test:deploy` and it's successfuly deployed and all tests work great.
And I lanched my API to Azure serverless that calls the functions of this contract and I am experiencing an issue named `Exceeded the prepaid gas`. when I call the `accept_offer` function.
The other function calls are working well such as `nft_mint` `nft_approve` `update_price` `offer` but when I am going to accept the offer, it shows this error.
https://explorer.testnet.near.org/transactions/DsVy8wRTgfyfAC3cVEC3a92AAtQczGP6im3YrBFbMun2
```
await account.functionCall({
contractId: marketId,
  methodName: 'accept_offer',
  args: {
    nft_contract_id: contractId,
    token_id,
    ft_token_id: 'near'
  },
  gas: GAS
});
```
GAS is 200TG like here. https://github.com/near-apps/nft-market/blob/main/src/config.js#L17

**Comment by mattlockyer** [comment]
![image](https://user-images.githubusercontent.com/321340/124619326-6a1b4a00-de2d-11eb-9770-aac5156ef7ca.png)

Looks like it's only attaching 30 Tgas to the call.

I am certain accept_offer takes more.

Please check to make sure GAS is defined in your app (or serverless function).

Is this defined?
![image](https://user-images.githubusercontent.com/321340/124619449-86b78200-de2d-11eb-879e-17cbb0ba27ce.png)
