### ISSUE TITLE
nft-market/contracts/nft-simple/src/lib.rs  measure_min_token_storage_cost some error?

### ISSUE THREAD

**Issue by wisarmy** [near-apps/nft-market#7]
code position: https://github.com/near-apps/nft-market/blob/50cd0e27bafbce2e8b17737bb1b12f8ec45d4209/contracts/nft-simple/src/lib.rs#L117

I think, the extra cost should be owner_id.len () - tmp_account_id.len ().
Should be
```rust
 let owner_id_extra_cost_in_bytes = (self.owner_id.len() - tmp_account_id.len()) as u64;
```

**Comment by mattlockyer** [comment]
if we did this it would be unsafe
tmp_account_id is 64 length, the max, owner_id cannot be longer.

TBH this method is a bit of a mess and this nft-simple contract is non-standard as it allows for "token types" and uses a bunch of additional storage.

You should check this source out:
https://github.com/near/near-sdk-rs/tree/master/near-contract-standards/src/non_fungible_token

and also this example:
https://github.com/near/near-sdk-rs/tree/master/examples/non-fungible-token/nft/src

**Comment by wisarmy** [comment]
https://github.com/near-apps/nft-market/blob/50cd0e27bafbce2e8b17737bb1b12f8ec45d4209/contracts/nft-simple/src/lib.rs#L119
Thank you for your answer, I was a little confused with the code snippet 116-119 below
```rust
        let tokens_per_owner_entry_in_bytes = env::storage_usage() - initial_storage_usage;
        let owner_id_extra_cost_in_bytes = (tmp_account_id.len() - self.owner_id.len()) as u64;

        self.extra_storage_in_bytes_per_token =
            tokens_per_owner_entry_in_bytes + owner_id_extra_cost_in_bytes;
```
If this is true, then the shorter the owner_id, the larger the variable owner_id_extra_cost_in_bytes, and the larger the self.extra_storage_in_bytes_per_token


In addition,

First, about
    this nft-simple contract is non-standard as it allows for "token types" and uses a bunch of additional storage.
can additional Storage be implemented using Indexer
Second, non_fungible_token in NEAR-SDK-RS has no royalty. I know the standard NEP-199, and I wonder if there is any relevant example
