### ISSUE TITLE
Standards sweep: nft_supply_for_owner

### ISSUE THREAD

**Issue by mikedotexe** [near-apps/nft-market#9]
Going through a cursory sweep to create issues and then we can divide and conquer on implementing them.

`nft_supply_for_owner` is not according to the standard, but just U64 needs to be U128: https://github.com/near-apps/nft-market/blob/4fb70e6a4f9b8db6fd51ccbc674dcfdcb2e1ba57/contracts/nft-simple/src/enumerable.rs#L69

https://nomicon.io/Standards/NonFungibleToken/Enumeration.html#interface

**Comment by mattlockyer** [comment]
![image](https://user-images.githubusercontent.com/321340/133354101-df4ff2cb-604d-44d5-b3de-b5b84a654576.png)

It really does seem that the standard is forcing some unnecessary conversions to u128 from .len() -> u64 under the hood.

https://github.com/near/near-sdk-rs/blob/95954cad746502aeb64e42a8bd5bbbb1ce0df8cc/near-contract-standards/src/non_fungible_token/enumeration/enumeration_impl.rs#L55-L56
